#!/bin/bash

if [[ "$*" =~ "--debug" ]];
then
    set -x
fi

PATH_TO_IAC=`pwd`
PROJECT_DIR="$(basename $PATH_TO_IAC)"
CONTAINER_WORKSPACE="/workspace/$PROJECT_DIR"

DOCKER_IMAGE_NAME="meterian/sasha"
if [[ "$*" =~ "--canary" ]];
then
    DOCKER_IMAGE_NAME="meterian/sasha-canary"
    echo "Using canary version of SASHA"
fi

VERSION="latest"
for arg in $*
do
    flagAndTag="$(expr "$arg" : '\(--image:.*\)')" || true
    maybeTag="$(echo "$flagAndTag" | cut -d: -f2)"
    if [[ "$maybeTag" != "" ]]; then
        VERSION="$maybeTag"
        echo "Requested usage of image '$DOCKER_IMAGE_NAME:$VERSION'"
    fi
done


DOCKER_FULL_IMAGE_NAME="$DOCKER_IMAGE_NAME:${VERSION}"

docker inspect --type=image $DOCKER_FULL_IMAGE_NAME  1>/dev/null 2>/dev/null 
if [ $? -ne 0 ]; then
    echo -n -e "Updating image...\r"
    docker pull --quiet $DOCKER_FULL_IMAGE_NAME 1>/dev/null 2>/dev/null
fi

docker run --rm \
    --volume "$PATH_TO_IAC":"$CONTAINER_WORKSPACE" \
    --workdir "$CONTAINER_WORKSPACE" \
    --env METERIAN_API_TOKEN=$METERIAN_API_TOKEN \
    --env CLIENT_VM_PARAMS="$CLIENT_VM_PARAMS" \
    --env METERIAN_ENV="$METERIAN_ENV" \
    --env METERIAN_PROTO="$METERIAN_PROTO" \
    --env METERIAN_DOMAIN="$METERIAN_DOMAIN" \
    --env HOST_UID=$(id -u) \
    --env HOST_GID=$(id -g) \
    $DOCKER_FULL_IMAGE_NAME $*
