#!/bin/bash

if [[ "$*" =~ "--debug" ]];
then
    set -x
fi

PATH_TO_IAC=`pwd`
PROJECT_DIR="$(basename $PATH_TO_IAC)"
CONTAINER_WORKSPACE="/workspace/$PROJECT_DIR"

VERSION="latest"
DOCKER_FULL_IMAGE_NAME="meterian/sasha:${VERSION}"

if [[ "$*" =~ "--canary" ]];
then
    DOCKER_FULL_IMAGE_NAME="meterian/sasha-canary:${VERSION}"
    echo "Using canary version of SASHA"
fi

docker inspect --type=image $DOCKER_FULL_IMAGE_NAME  1>/dev/null 2>/dev/null 
if [ $? -ne 0 ]; then
    echo -n -e "Updating image...\r"
    docker pull --quiet $DOCKER_FULL_IMAGE_NAME 1>/dev/null 2>/dev/null
fi

docker run --rm -it \
    --volume "$PATH_TO_IAC":"$CONTAINER_WORKSPACE" \
    --workdir "$CONTAINER_WORKSPACE" \
    --env METERIAN_API_TOKEN=$METERIAN_API_TOKEN \
    --env CLIENT_VM_PARAMS="$CLIENT_VM_PARAMS" \
    --env METERIAN_ENV="$METERIAN_ENV" \
    --env METERIAN_PROTO="$METERIAN_PROTO" \
    --env METERIAN_DOMAIN="$METERIAN_DOMAIN" \
    --env HOST_UID=$(id -u) \
    --env HOST_GID=$(id -g) \
    $DOCKER_FULL_IMAGE_NAME $*
